In [1]:
import requests
import pandas as pd

I pulled in the data from an API then described.

In [2]:
r = requests.get("https://harry-potter-api-en.onrender.com/characters")
df = pd.read_json("https://harry-potter-api-en.onrender.com/characters") 
print (df)
df.describe()

    id                                character    nickname  hogwartsStudent  \
0    1                       Harry James Potter       Harry             True
1    2                    Hermione Jean Granger    Hermione             True
2    3                              Ron Weasley         Ron             True
3    4                             Fred Weasley        Fred             True
4    5                           George Weasley      George             True
5    6                             Bill Weasley        Bill             True
6    7                            Percy Weasley       Percy             True
7    8                          Charlie Weasley     Charlie             True
8    9                            Ginny Weasley       Ginny             True
9   10                            Molly Weasley       Molly             True
10  11                           Arthur Weasley      Arthur             True
11  12                       Neville Longbottom     Neville             True
12  13                            Luna Lovegood        Luna             True
13  14                             Draco Malfoy       Draco             True
14  15  Albus Percival Wulfric Brian Dumbledore  Dumbledore             True
15  16                       Minerva McGonagall     Minerva             True
16  17                              Remus Lupin       Lupin             True
17  18                            Rubeus Hagrid      Hagrid             True
18  19                             Sirius Black      Sirius             True
19  20                            Severus Snape       Snape             True
20  21                      Bellatrix Lestrange       Bella             True
21  22                           Lord Voldemort   Voldemort             True
22  23                              Argus Filch       Filch            False

   hogwartsHouse         interpretedBy  \
0     Gryffindor      Daniel Radcliffe
1     Gryffindor           Emma Watson
2     Gryffindor          Rupert Grint
3     Gryffindor          James Phelps
4     Gryffindor         Oliver Phelps
5     Gryffindor      Domhnall Gleeson
6     Gryffindor          Chris Rankin
7     Gryffindor               ninguno
8     Gryffindor          Bonnie Right
9     Gryffindor         Julie Walters
10    Gryffindor         Mark Williams
11    Gryffindor         Matthew Lewis
12     Ravenclaw          Evanna Lynch
13     Slytherin            Tom Felton
14    Gryffindor        Richard Harris
15    Gryffindor          Maggie Smith
16    Gryffindor         David Thewils
17    Gryffindor       Robbie Coltrane
18    Gryffindor           Gary Oldman
19     Slytherin          Alan Rickman
20     Slytherin  Helena Bonham Carter
21     Slytherin         Ralph Fiennes
22       ninguna         David Bradley

                                                child  \
0   [James Sirius Potter, Albus Severus Potter, Li...
1        [Rose Granger-Weasley, Hugo Granger-Weasley]
2        [Rose Granger-Weasley, Hugo Granger-Weasley]
3                                                  []
4                                                  []
5                                                  []
6                                                  []
7                                                  []
8   [James Sirius Potter, Albus Severus Potter, Li...
9   [Ron Weasley, Fred Weasley, George Weasley, Bi...
10  [Ron Weasley, Fred Weasley, George Weasley, Bi...
11                                                 []
12                                                 []
13                                  [Scorpius Malfoy]
14                                                 []
15                                                 []
16                                        [Ted Lupin]
17                                                 []
18                                                 []
19                                                 []
20                                           [Delphi]
21                                           [Delphi]
22                                                 []

                                                image
0   https://raw.githubusercontent.com/fedeperin/ha...
1   https://raw.githubusercontent.com/fedeperin/ha...
2   https://raw.githubusercontent.com/fedeperin/ha...
3   https://raw.githubusercontent.com/fedeperin/ha...
4   https://raw.githubusercontent.com/fedeperin/ha...
5   https://raw.githubusercontent.com/fedeperin/ha...
6   https://raw.githubusercontent.com/fedeperin/ha...
7   https://raw.githubusercontent.com/fedeperin/ha...
8   https://raw.githubusercontent.com/fedeperin/ha...
9   https://raw.githubusercontent.com/fedeperin/ha...
10  https://raw.githubusercontent.com/fedeperin/ha...
11  https://raw.githubusercontent.com/fedeperin/ha...
12  https://raw.githubusercontent.com/fedeperin/ha...
13  https://raw.githubusercontent.com/fedeperin/ha...
14  https://raw.githubusercontent.com/fedeperin/ha...
15  https://raw.githubusercontent.com/fedeperin/ha...
16  https://raw.githubusercontent.com/fedeperin/ha...
17  https://raw.githubusercontent.com/fedeperin/ha...
18  https://raw.githubusercontent.com/fedeperin/ha...
19  https://raw.githubusercontent.com/fedeperin/ha...
20  https://raw.githubusercontent.com/fedeperin/ha...
21  https://raw.githubusercontent.com/fedeperin/ha...
22  https://raw.githubusercontent.com/fedeperin/ha...

             id
count  23.00000
mean   12.00000
std     6.78233
min     1.00000
25%     6.50000
50%    12.00000
75%    17.50000
max    23.00000

I pulled in the data from an API. I wrangled the data to only show characters that were never a Howgarts student.

In [3]:
r = requests.get("https://harry-potter-api-en.onrender.com/characters")
df = pd.read_json("https://harry-potter-api-en.onrender.com/characters") 
df = df.loc[df['hogwartsStudent']== False,:]
print (df)

    id    character nickname  hogwartsStudent hogwartsHouse  interpretedBy  \
22  23  Argus Filch    Filch            False       ninguna  David Bradley

   child                                              image
22    []  https://raw.githubusercontent.com/fedeperin/ha...

I pulled in data from an API. I wrangled the data to only show characters that were from house Slytherin and described the data.

In [4]:
r = requests.get("https://harry-potter-api-en.onrender.com/characters")
df = pd.read_json("https://harry-potter-api-en.onrender.com/characters") 
df = df.loc[df['hogwartsHouse']== 'Slytherin',]
print (df)
df.describe()

    id            character   nickname  hogwartsStudent hogwartsHouse  \
13  14         Draco Malfoy      Draco             True     Slytherin
19  20        Severus Snape      Snape             True     Slytherin
20  21  Bellatrix Lestrange      Bella             True     Slytherin
21  22       Lord Voldemort  Voldemort             True     Slytherin

           interpretedBy              child  \
13            Tom Felton  [Scorpius Malfoy]
19          Alan Rickman                 []
20  Helena Bonham Carter           [Delphi]
21         Ralph Fiennes           [Delphi]

                                                image
13  https://raw.githubusercontent.com/fedeperin/ha...
19  https://raw.githubusercontent.com/fedeperin/ha...
20  https://raw.githubusercontent.com/fedeperin/ha...
21  https://raw.githubusercontent.com/fedeperin/ha...

              id
count   4.000000
mean   19.250000
std     3.593976
min    14.000000
25%    18.500000
50%    20.500000
75%    21.250000
max    22.000000

I pulled in data from an API. I wrangled the data to only show characters that were from house Gryffindor and described the data.

In [5]:
r = requests.get("https://harry-potter-api-en.onrender.com/characters")
df = pd.read_json("https://harry-potter-api-en.onrender.com/characters") 
df = df.loc[df['hogwartsHouse']== 'Gryffindor',]
print (df)
df.describe()

    id                                character    nickname  hogwartsStudent  \
0    1                       Harry James Potter       Harry             True
1    2                    Hermione Jean Granger    Hermione             True
2    3                              Ron Weasley         Ron             True
3    4                             Fred Weasley        Fred             True
4    5                           George Weasley      George             True
5    6                             Bill Weasley        Bill             True
6    7                            Percy Weasley       Percy             True
7    8                          Charlie Weasley     Charlie             True
8    9                            Ginny Weasley       Ginny             True
9   10                            Molly Weasley       Molly             True
10  11                           Arthur Weasley      Arthur             True
11  12                       Neville Longbottom     Neville             True
14  15  Albus Percival Wulfric Brian Dumbledore  Dumbledore             True
15  16                       Minerva McGonagall     Minerva             True
16  17                              Remus Lupin       Lupin             True
17  18                            Rubeus Hagrid      Hagrid             True
18  19                             Sirius Black      Sirius             True

   hogwartsHouse     interpretedBy  \
0     Gryffindor  Daniel Radcliffe
1     Gryffindor       Emma Watson
2     Gryffindor      Rupert Grint
3     Gryffindor      James Phelps
4     Gryffindor     Oliver Phelps
5     Gryffindor  Domhnall Gleeson
6     Gryffindor      Chris Rankin
7     Gryffindor           ninguno
8     Gryffindor      Bonnie Right
9     Gryffindor     Julie Walters
10    Gryffindor     Mark Williams
11    Gryffindor     Matthew Lewis
14    Gryffindor    Richard Harris
15    Gryffindor      Maggie Smith
16    Gryffindor     David Thewils
17    Gryffindor   Robbie Coltrane
18    Gryffindor       Gary Oldman

                                                child  \
0   [James Sirius Potter, Albus Severus Potter, Li...
1        [Rose Granger-Weasley, Hugo Granger-Weasley]
2        [Rose Granger-Weasley, Hugo Granger-Weasley]
3                                                  []
4                                                  []
5                                                  []
6                                                  []
7                                                  []
8   [James Sirius Potter, Albus Severus Potter, Li...
9   [Ron Weasley, Fred Weasley, George Weasley, Bi...
10  [Ron Weasley, Fred Weasley, George Weasley, Bi...
11                                                 []
14                                                 []
15                                                 []
16                                        [Ted Lupin]
17                                                 []
18                                                 []

                                                image
0   https://raw.githubusercontent.com/fedeperin/ha...
1   https://raw.githubusercontent.com/fedeperin/ha...
2   https://raw.githubusercontent.com/fedeperin/ha...
3   https://raw.githubusercontent.com/fedeperin/ha...
4   https://raw.githubusercontent.com/fedeperin/ha...
5   https://raw.githubusercontent.com/fedeperin/ha...
6   https://raw.githubusercontent.com/fedeperin/ha...
7   https://raw.githubusercontent.com/fedeperin/ha...
8   https://raw.githubusercontent.com/fedeperin/ha...
9   https://raw.githubusercontent.com/fedeperin/ha...
10  https://raw.githubusercontent.com/fedeperin/ha...
11  https://raw.githubusercontent.com/fedeperin/ha...
14  https://raw.githubusercontent.com/fedeperin/ha...
15  https://raw.githubusercontent.com/fedeperin/ha...
16  https://raw.githubusercontent.com/fedeperin/ha...
17  https://raw.githubusercontent.com/fedeperin/ha...
18  https://raw.githubusercontent.com/fedeperin/ha...

              id
count  17.000000
mean    9.588235
std     5.820855
min     1.000000
25%     5.000000
50%     9.000000
75%    15.000000
max    19.000000

Selected and printed the SECOND AND THIRD columns of my data frame.

In [6]:
r = requests.get("https://harry-potter-api-en.onrender.com/characters")
df = pd.read_json("https://harry-potter-api-en.onrender.com/characters")
df[['nickname','hogwartsStudent']].head()

   nickname  hogwartsStudent
0     Harry             True
1  Hermione             True
2       Ron             True
3      Fred             True
4    George             True

Selected and printed the FIRST 4 rows of my data frame.

In [7]:
r = requests.get("https://harry-potter-api-en.onrender.com/characters")
df = pd.read_json("https://harry-potter-api-en.onrender.com/characters")
df.head (4)

,id,character,nickname,hogwartsStudent,hogwartsHouse,interpretedBy,child,image
0,1,Harry James Potter,Harry,True,Gryffindor,Daniel Radcliffe,"[James Sirius Potter, Albus Severus Potter, Li...",https://raw.githubusercontent.com/fedeperin/ha...
1,2,Hermione Jean Granger,Hermione,True,Gryffindor,Emma Watson,"[Rose Granger-Weasley, Hugo Granger-Weasley]",https://raw.githubusercontent.com/fedeperin/ha...
2,3,Ron Weasley,Ron,True,Gryffindor,Rupert Grint,"[Rose Granger-Weasley, Hugo Granger-Weasley]",https://raw.githubusercontent.com/fedeperin/ha...
3,4,Fred Weasley,Fred,True,Gryffindor,James Phelps,[],https://raw.githubusercontent.com/fedeperin/ha...